version: '3'

services:
  kedro:
    image: asi/kedro:dev
    build:
      context: kedro
    volumes:
      - ./kedro:/home/kedro_docker
  mlflow:
    image: asi/kedro:dev
    build:
      context: kedro
    volumes:
      - ./kedro:/home/kedro_docker
    command: mlflow ui -h 0.0.0.0 -p 5000 --expose-prometheus metrics
    ports:
      - '5000:5000'  
  streamlit:
    image: asi/streamlit:dev
    build:
      context: streamlit
    volumes:
      - ./streamlit:/srv/streamlit
      - ./kedro/data/06_models:/srv/streamlit/model
    ports:
      - '8501:8501'
    networks:
      - asi
    depends_on:
      - kedro
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
networks:
  asi:
