version: '3'
services:
  generator:
    build:
      context: .
      target: generator
    environment:
      NOCASES: 10
      OUTPUT_FILE: /data/raw/first.csv
    volumes:
      - ./data:/data:rw
  cleaner:
    build:
      context: .
      target: cleaner
    environment:
      FROM_FILE: /data/raw/first.csv
      OUTPUT_FILE: /data/clean/first.csv
    volumes:
      - ./data:/data:rw

