version: '3'
services:
  baseimg:
    build:
      context: .
      target: base
  generator:
    build:
      context: .
      target: generator
    environment:
      NOCASES: 5000
      OUTPUT_FILE: /data/raw/first.csv
    volumes:
      - ./data:/data:rw
    depends_on:
      - baseimg
  cleaner:
    build:
      context: .
      target: cleaner
    environment:
      RAW: /data/raw/first.csv
      CLEAN_FILE: /data/clean/first.csv
    volumes:
      - ./data:/data:rw
    depends_on:
      - baseimg
  trainer:
    build:
      context: .
      target: trainer
    environment:
      INPUT_FILE: /data/raw/first.csv
      MODEL_OUT: /data/model/model.scops
    volumes:
      - ./data:/data:rw
    depends_on:
      - baseimg

